"""The art, as code: the box helicopter and the box crate the gametests and the booth fly, and
the templates they fly in. (The sling container's model, the sprayer's icon and the sounds join
this file as they are made.)

Run from the repository root:

    uv run --no-project python devtools/art/build.py

Everything it writes is committed; this script is the source of truth for those files. All
original work. Copyright 2026 Rusty Shackleford and nfx. SPDX-License-Identifier: AGPL-3.0-or-later.
"""
from __future__ import annotations

import json
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TEST = "rotorcraft_gametest"
TEST_ASSETS = ROOT / "src/gametest/resources/assets" / TEST
TEST_DATA = ROOT / "src/gametest/resources/data" / TEST


# ---------------------------------------------------------------- PNG writing

def write_png(path: Path, width: int, height: int, pixels) -> None:
    """pixels: rows of (r, g, b, a) tuples, top row first."""
    raw = b"".join(b"\x00" + b"".join(bytes(p) for p in row) for row in pixels)

    def chunk(kind: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + kind + data
                + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))

    png = (b"\x89PNG\r\n\x1a\n"
           + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 6, 0, 0, 0))
           + chunk(b"IDAT", zlib.compress(raw, 9))
           + chunk(b"IEND", b""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


class Noise:
    """A deterministic grain so flat colours read as material, not plastic."""

    def __init__(self, seed: int) -> None:
        self.state = seed & 0xFFFFFFFF

    def next(self) -> float:
        self.state = (1664525 * self.state + 1013904223) & 0xFFFFFFFF
        return self.state / 0xFFFFFFFF


def shade(rgb, delta):
    return tuple(max(0, min(255, c + delta)) for c in rgb)


# ------------------------------------------------------- the test vehicles' atlas

# A 4 x 4 grid of 16-pixel swatches; a face takes one swatch whole, inset so no coordinate
# sits on a swatch's edge (Vanilla Wheels' rule: the cutout shader drops a face that samples
# the atlas's empty padding).
CELLS = {"body": (0, 0), "trim": (1, 0), "glass": (2, 0), "lamp": (3, 0),
         "rotor": (0, 1), "metal": (1, 1), "boom": (2, 1), "door": (3, 1)}
COLOURS = {"body": (200, 200, 200), "trim": (70, 74, 80), "glass": (150, 200, 230), "lamp": (250, 240, 200),
           "rotor": (36, 36, 40), "metal": (130, 136, 146), "boom": (190, 170, 60), "door": (180, 180, 180)}


def atlas():
    noise = Noise(0x4E11)
    px = [[(0, 0, 0, 0) for _ in range(64)] for _ in range(64)]
    for name, (cx, cy) in CELLS.items():
        base = COLOURS[name]
        alpha = 160 if name == "glass" else 255
        for y in range(16):
            for x in range(16):
                px[cy * 16 + y][cx * 16 + x] = (*shade(base, int((noise.next() - 0.5) * 16)), alpha)
    return px


class ObjWriter:
    def __init__(self, what: str) -> None:
        self.lines = [f"# generated by devtools/art/build.py: {what}"]
        self.v = 0
        self.vt = 0

    def box(self, material, group, x0, y0, z0, x1, y1, z1):
        """A closed box from (x0,y0,z0) to (x1,y1,z1), six quads on one swatch, wound outward."""
        cx, cy = CELLS[material]
        inset = 0.02
        u0, v0 = cx / 4 + inset / 4, 1 - (cy + 1) / 4 + inset / 4
        u1, v1 = (cx + 1) / 4 - inset / 4, 1 - cy / 4 - inset / 4
        corners = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0), (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
        for c in corners:
            self.lines.append("v %.3f %.3f %.3f" % c)
        for (u, vv) in ((u0, v0), (u1, v0), (u1, v1), (u0, v1)):
            self.lines.append("vt %.4f %.4f" % (u, vv))
        base_v = self.v
        base_t = self.vt
        self.lines.append(f"usemtl {material}")
        self.lines.append(f"g {group}")
        faces = [(1, 4, 3, 2), (5, 6, 7, 8), (1, 2, 6, 5), (3, 4, 8, 7), (2, 3, 7, 6), (1, 5, 8, 4)]
        for f in faces:
            self.lines.append("f " + " ".join(f"{base_v + i}/{base_t + k + 1}" for k, i in enumerate(f)))
        self.v += 8
        self.vt += 4

    def text(self):
        return "\n".join(self.lines) + "\n"


def box_heli():
    """A cabin, a tail boom, skids, a two-bladed rotor on a mast, a tail rotor, a spray boom."""
    w = ObjWriter("the box helicopter")
    w.box("body", "body", -12, 4, -8, 12, 26, 24)              # the cabin: 1.5 wide, 2 long
    w.box("glass", "cab", -11, 10, 24, 11, 22, 24.5)           # the windscreen
    w.box("lamp", "lamps", -2, 4, 24, 2, 6, 24.5)               # the landing light
    w.box("body", "body", -3, 16, -40, 3, 22, -8)               # the tail boom
    w.box("body", "body", -1, 22, -40, 1, 30, -34)              # the fin
    w.box("trim", "skids", -11, 0, -10, -9, 2, 20)              # left skid
    w.box("trim", "skids", 9, 0, -10, 11, 2, 20)                # right skid
    w.box("trim", "skids", -10, 2, 10, 10, 4, 12)               # front cross tube
    w.box("trim", "skids", -10, 2, -2, 10, 4, 0)                # rear cross tube
    w.box("metal", "rotor_main", -1, 26, 3, 1, 31, 5)           # the mast
    w.box("rotor", "rotor_main", -40, 30.5, 3, 40, 31.5, 5)     # the blades, 5 blocks across, about (0, 30, 4)
    w.box("rotor", "rotor_tail", 3, 20.5, -39, 4, 21.5, -37)    # the tail rotor's hub
    w.box("rotor", "rotor_tail", 3.5, 16, -38.5, 4, 26, -37.5)  # its blade, turning about x through (3.75, 21, -38)
    w.box("boom", "spray_boom", -28, 4, -11, 28, 5, -9)         # the spray boom, 3.5 blocks across
    return w.text()


def box_crate():
    """A box on four feet with a door at the back, a ring on top for the rope."""
    w = ObjWriter("the box crate")
    w.box("trim", "floor", -12, 2, -20, 12, 4, 20)              # the floor
    w.box("body", "wall", 11, 4, -20, 12, 22, 20)               # left wall
    w.box("body", "wall", -12, 4, -20, -11, 22, 20)             # right wall
    w.box("body", "wall", -12, 4, 19, 12, 22, 20)               # front wall
    w.box("body", "roof", -12, 22, -20, 12, 24, 20)             # the roof
    w.box("door", "door", -11, 4, -20.5, 11, 22, -19.5)         # the door, hinged at its right edge
    for x in (-11, 9):
        for z in (-19, 17):
            w.box("metal", "feet", x, 0, z, x + 2, 2, z + 2)   # the feet
    w.box("metal", "ring", -1, 24, -1, 1, 27, 1)                # the lift ring
    return w.text()


BOX_HELI = {
    "mesh": f"{TEST}:box_heli",
    "texture": f"{TEST}:textures/entity/box_heli.png",
    "scale": 0.0625,
    "handedness": "right",
    "body": {"width": 1.5, "length": 4.0, "height": 1.6,
             "parts": [{"at": [0, 4, 16], "width": 1.5, "height": 1.4}, {"at": [0, 16, -26], "width": 0.6, "height": 0.6}]},
    "seats": [{"at": [-5, 8, 12], "driver": True}, {"at": [5, 8, 12]}, {"at": [0, 8, 0]}],
    "wheels": {"radius": 1, "drawn": False,
               "positions": [{"forward": 18, "right": -10}, {"forward": 18, "right": 10},
                             {"forward": -8, "right": -10}, {"forward": -8, "right": 10}]},
    "engine": {"max_speed": 1.0, "acceleration": 0.03, "reverse_speed": 0.3, "brake": 0.04},
    "climb": 0.5,
    "mass": 2.0,
    "fuel": {"capacity": 24000},
    "headlights": {"at": [[0, 5, 24.5]], "part": {"material": "lamp"}, "range": 10},
    "paint": {"part": {"material": "body"}, "default": "green"},
    "glass": {"material": "glass"},
}

BOX_HELI_FLIGHT = {
    "climb_rate": 0.4, "descent_rate": 0.5, "vertical_acceleration": 0.03,
    "yaw_rate": 4.0, "spool_ticks": 40, "tilt": 10,
    "rotors": [{"part": {"group": "rotor_main"}, "pivot": [0, 30, 4], "axis": [0, 1, 0], "speed": 1.0},
               {"part": {"group": "rotor_tail"}, "pivot": [3.75, 21, -38], "axis": [1, 0, 0], "speed": 3.0}],
    "hook": [0, 2, 8],
    "sprayer": {"part": {"group": "spray_boom"}, "at": [0, 4, -10], "width": 7},
}

BOX_CRATE = {
    "mesh": f"{TEST}:box_crate",
    "texture": f"{TEST}:textures/entity/box_heli.png",
    "scale": 0.0625,
    "handedness": "right",
    "body": {"width": 1.5, "length": 2.5, "height": 1.5, "parts": []},
    "seats": [],
    "wheels": {"radius": 1, "drawn": False,
               "positions": [{"forward": 18, "right": -10}, {"forward": 18, "right": 10},
                             {"forward": -18, "right": -10}, {"forward": -18, "right": 10}]},
    "climb": 0.5,
    "mass": 1.0,
    "cargo": {"adults": 2, "young": 4, "slots": [[0, 4, 8], [0, 4, -8]]},
    "doors": [{"part": {"group": "door"}, "hinge": [-11, 4, -20], "axis": [0, 1, 0], "open": 1.6,
               "from": [-11, 4, -20.5], "to": [11, 22, -19.5]}],
    "storage": {"chests": [{"at": [0, 4, 10], "yaw": 180, "scale": 0.4, "rows": 3}]},
    "paint": {"part": {"material": "body"}, "default": "orange"},
}

BOX_CRATE_SLING = {"lift": [0, 27, 0], "rope": 3.0}


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def template(path: Path, size) -> None:
    """An empty template of air, size [x, y, z]: the tests lay their own ground."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{DataVersion: 3955, size: [%d, %d, %d], data: [], entities: [], palette: [{Name: \"minecraft:air\"}]}\n" % tuple(size), encoding="utf-8")


def main(argv) -> None:
    mesh = TEST_ASSETS / "vanillawheels/mesh"
    mesh.mkdir(parents=True, exist_ok=True)
    (mesh / "box_heli.obj").write_text(box_heli(), encoding="utf-8")
    (mesh / "box_crate.obj").write_text(box_crate(), encoding="utf-8")
    write_png(TEST_ASSETS / "textures/entity/box_heli.png", 64, 64, atlas())
    write_json(TEST_DATA / "vanillawheels/vehicle/box_heli.json", BOX_HELI)
    write_json(TEST_DATA / "rotorcraft/aircraft/box_heli.json", BOX_HELI_FLIGHT)
    write_json(TEST_DATA / "vanillawheels/vehicle/box_crate.json", BOX_CRATE)
    write_json(TEST_DATA / "rotorcraft/sling_load/box_crate.json", BOX_CRATE_SLING)
    write_json(TEST_ASSETS / "lang/en_us.json", {"vehicle.rotorcraft_gametest.box_heli": "Box Helicopter",
                                                  "vehicle.rotorcraft_gametest.box_crate": "Box Crate"})
    template(ROOT / "devtools/gameteststructures/airfield.snbt", (40, 40, 40))
    template(ROOT / "devtools/gameteststructures/farm.snbt", (24, 24, 24))


if __name__ == "__main__":
    main(sys.argv)
